name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and push Docker image
        run: |
          docker build -t your_dockerhub_username/fastapi-book-project:latest .
          docker push your_dockerhub_username/fastapi-book-project:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Deploy to server
        run: |
          ssh user@${{ secrets.SERVER_IP }} 'docker pull your_dockerhub_username/fastapi-book-project:latest && docker-compose -f /path/to/docker-compose.yml up -d'
